### ISSUE TITLE
Error attempting to use AmazonS3EncryptionV2 and Authenticated Encryption

### ISSUE THREAD

**Issue by ldadams** [awsdocs/amazon-s3-developer-guide#113]
Regardless of what version of Bouncy Castle I pull in I can't get past this runtime error.  1.8 Sources and JDK 14.  Using the maven-assembly-plugin to assemble a single Jar.

Thanks in advance for any help.

```
Exception in thread "main" java.lang.UnsupportedOperationException: A more recent version of Bouncy castle is required for authenticated encryption.
	at com.amazonaws.services.s3.model.CryptoConfigurationV2.checkBountyCastle(CryptoConfigurationV2.java:379)
	at com.amazonaws.services.s3.model.CryptoConfigurationV2.checkCryptoMode(CryptoConfigurationV2.java:366)
	at com.amazonaws.services.s3.model.CryptoConfigurationV2.<init>(CryptoConfigurationV2.java:68)
	at com.amazonaws.services.s3.model.CryptoConfigurationV2.<init>(CryptoConfigurationV2.java:47)
	at securities.CryptoUtil.Encrypt(CryptoUtil.java:41)
	at securities.App.main(App.java:19)
```

   
```
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
        keyPairGenerator.initialize(2048);

        KeyPair keyPair = keyPairGenerator.generateKeyPair();

        String s3ObjectKey = "test.txt";
        String s3ObjectContent = "This should be encrypt";

        AmazonS3EncryptionV2 s3EncryptionClientV2 = AmazonS3EncryptionClientV2Builder.standard()
                .withRegion(Regions.DEFAULT_REGION)
                .withClientConfiguration(new ClientConfiguration())
                .withCryptoConfiguration(new CryptoConfigurationV2().withCryptoMode(CryptoMode.AuthenticatedEncryption))
                .withEncryptionMaterialsProvider(new StaticEncryptionMaterialsProvider(new EncryptionMaterials(keyPair)))
                .build();

        s3EncryptionClientV2.putObject(bucketName, s3ObjectKey, s3ObjectContent);
        s3EncryptionClientV2.shutdown();

        return s3EncryptionClientV2.getObjectAsString(bucketName, s3ObjectKey);
```

```
   <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.11.877</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-kms</artifactId>
            <version>1.11.877</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.877</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-ext-jdk15on</artifactId>
            <version>1.66</version>
        </dependency>
    </dependencies>
```

**Comment by panjws** [comment]
ldadams sounds like a support issue rather than a documentation issue.

If you want further support, you can:
•	Post your questions on the [Amazon S3 discussion forum](https://forums.aws.amazon.com/tags/s3?categoryID=1)
•	Or contact [AWSSupport](https://aws.amazon.com/contact-us/)

If there is something specific missing in our docs, please let us know.

Best regards and thanks for being an AWS Customer.
